### ISSUE TITLE
http/https protocols are not supported 

### ISSUE THREAD

**Issue by amarouane-ABDLHAK** [cumulus-nasa/cumulus#104]
https://github.com/cumulus-nasa/cumulus/tree/master/cumulus/tasks/discover-granules  function throws the following  error when using a provider with http/https protocol
{
    "level": 50,
    "time": 1513367217626,
    "msg": "Protocol http is not supported.",
    "pid": 1,
    "hostname": "ip-**-**-***-***",
    "name": "cumulus",
    "file": "discover-granules/index.js",
    "type": "Error",
    "stack": "Error: Protocol http is not supported.\n    at Object.selector (/var/task/discover-granules/index.js:21486:16)\n    at handler (/var/task/discover-granules/index.js:8900:31)",
    "v": 1
}

**Comment by abarciauskas-bgse** [comment]
Fixed in https://github.com/cumulus-nasa/cumulus/pull/116
