### ISSUE TITLE
Cumulus wiki links incorrect 

### ISSUE THREAD

**Issue by dneufeldcu** [cumulus-nasa/cumulus#139]
When clicking to review schema examples, the links are incorrect and return 404.

e.g.:
https://cumulus-nasa.github.io/schemas/schemas/example-data/example-message-envelope.json

should be:
https://cumulus-nasa.github.io/schemas/example-data/example-message-envelope.json

**Comment by laurenfrederick** [comment]
Created a JIRA issue to resolve this. Thank you!

**Comment by scisco** [comment]
fixed
